Add unit tests for DynamoUtils.java
Diffblue-benchmarks/amazon-kinesis-client pull request #1
Opened 2018-11-16 09:14 UTC by James-Adam

Adding unit tests for DynamoUtil.java

Waiting on Mel to be back in next week to get information on how to deal with license headers and such for this one. 

More tests for this class exist but use Mocking/member matching and i'm going to avoid pulling in any extra dependencies for this project - it's all done via a remote pom so I don't want to interfere too much. 

`By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.`

2018-11-16 09:19 UTC, paulkennethkent commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +}
newline

2018-11-16 09:25 UTC, JohnLBergqvist requested changes
A lot of redundant tests, given you have multiple tests for the same functions that assert `null`. Would be best to trim these down I feel.

2018-11-16 09:36 UTC, petersear reviewed
Agree with John's comment, otherwise looks good.

2018-11-16 13:41 UTC, JohnLBergqvist requested changes

2018-11-16 13:41 UTC, JohnBergqvist commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +    final String key = "!E\"%";
This test is unnecessary - duplicates the one above essentially

2018-11-16 14:23 UTC, petersear requested changes
I've marked some tests as being similar to others ie. same inputs and assert for the same function.

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +  public void safeGetSSInput1NotNullOutput2() {
Similar to safeGetSSInput1NotNullOutput()

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +  public void safeGetSSInput1NotNullOutput3() {
Similar to safeGetSSInput1NotNullOutput()

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +  public void safeGetSSInput1NotNullOutput4() {
Similar to safeGetSSInput1NotNullOutput()

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +  public void safeGetSSInput1NotNullOutput5() {
Similar to safeGetSSInput1NotNullOutput()

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +    dynamoRecord.put("aAAAA", null);
Similar to safeGetLongInput1NotNullOutputNull()

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +  public void safeGetLongInput1NotNullOutputNull3() {
Similar to safeGetLongInput1NotNullOutputNull()

2018-11-16 14:23 UTC, petersear commented on amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/DynamoUtilsTest.java
> +  public void safeGetLongInput1NotNullOutputNull6() {
Similar to safeGetLongInput1NotNullOutputNull2()

2018-11-19 14:29 UTC, petersear approved these changes

2018-11-20 11:15 UTC, JohnLBergqvist approved these changes

2018-11-20 13:48 UTC, closed without merging